/*
 * Copyright (c) 2009-2010 DuraSpace. All rights reserved.
 */
package org.duracloud.account.common.domain;

/**
 * @author "Daniel Bernstein (dbernstein@duraspace.org)"
 */
public class AccountInfo extends BaseDomainData implements Comparable<AccountInfo> {

    public enum AccountStatus {
        PENDING, ACTIVE, INACTIVE, CANCELLED;
    }

    /*
     * The subdomain of duracloud.org which will be used to access the instance
     * associated with this account
     */
    private String subdomain;

    /*
     * The display name of the account
     */
    private String acctName;

    /*
     * The name of the organization responsible for the content in this account
     */
    private String orgName;

    /*
     * The name of the department (if applicable) of the organization
     * responsible for the content in this account
     */
    private String department;

    /*
     * The ID of the PaymentInfo which tracks the payment details for this
     * account
     */
    private int paymentInfoId;

    /*
     * The current status of this account
     */
    private AccountStatus status;

    /*
     * The type of account
     */
    private AccountType type;

    /*
     * The ID of the details needed to manage servers associated with this
     * account
     */
    private int serverDetailsId;

    /*
     * The ID of the cluster of accounts to which this account belongs
     */
    private int accountClusterId;

	public AccountInfo(int id,
                       String subdomain,
                       String acctName,
                       String orgName,
			           String department,
                       int paymentInfoId,
                       int serverDetailsId,
                       int accountClusterId,
                       AccountStatus status,
                       AccountType type) {
		this(id,
             subdomain,
             acctName,
             orgName,
             department,
             paymentInfoId,
             serverDetailsId,
             accountClusterId,
             status,
             type,
             0);
	}

    public AccountInfo(int id,
                       String subdomain,
                       String acctName,
                       String orgName,
                       String department,
                       int paymentInfoId,
                       int serverDetailsId,
                       int accountClusterId,
                       AccountStatus status,
                       AccountType type,
                       int counter) {
		super();
		this.id = id;
		this.subdomain = subdomain;
		this.acctName = acctName;
		this.orgName = orgName;
		this.department = department;
        this.paymentInfoId = paymentInfoId;
        this.status = status;
        this.type = type;
        this.serverDetailsId = serverDetailsId;
        this.accountClusterId = accountClusterId;
        this.counter = counter;
	}

    public String getSubdomain() {
        return subdomain;
    }

    public String getAcctName() {
        return acctName;
    }

    public void setAcctName(String acctName) {
        this.acctName = acctName;
    }

    public String getOrgName() {
        return orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }    

    public int getPaymentInfoId() {
        return paymentInfoId;
    }

    public AccountStatus getStatus() {
        return status;
    }

    public void setStatus(AccountStatus status) {
        this.status = status;
    }

    public AccountType getType() {
        return type;
    }

    public void setServerDetailsId(int serverDetailsId) {
        this.serverDetailsId = serverDetailsId;
    }

    public int getServerDetailsId() {
        return serverDetailsId;
    }

    public int getAccountClusterId() {
        return accountClusterId;
    }

    public void setAccountClusterId(int accountClusterId) {
        this.accountClusterId = accountClusterId;
    }

    @Override
    public int compareTo(AccountInfo o) {
        return this.acctName.compareTo(o.acctName);
    }

    /*
     * Generated by IntelliJ
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        AccountInfo that = (AccountInfo) o;

        if (accountClusterId != that.accountClusterId) {
            return false;
        }
        if (paymentInfoId != that.paymentInfoId) {
            return false;
        }
        if (serverDetailsId != that.serverDetailsId) {
            return false;
        }
        if (acctName != null ? !acctName.equals(that.acctName) :
            that.acctName != null) {
            return false;
        }
        if (department != null ? !department.equals(that.department) :
            that.department != null) {
            return false;
        }
        if (orgName != null ? !orgName.equals(that.orgName) :
            that.orgName != null) {
            return false;
        }
        if (status != that.status) {
            return false;
        }
        if (subdomain != null ? !subdomain.equals(that.subdomain) :
            that.subdomain != null) {
            return false;
        }
        if (type != that.type) {
            return false;
        }

        return true;
    }

    /*
     * Generated by IntelliJ
     */
    @Override
    public int hashCode() {
        int result = subdomain != null ? subdomain.hashCode() : 0;
        result = 31 * result + (acctName != null ? acctName.hashCode() : 0);
        result = 31 * result + (orgName != null ? orgName.hashCode() : 0);
        result = 31 * result + (department != null ? department.hashCode() : 0);
        result = 31 * result + paymentInfoId;
        result = 31 * result + (status != null ? status.hashCode() : 0);
        result = 31 * result + (type != null ? type.hashCode() : 0);
        result = 31 * result + serverDetailsId;
        result = 31 * result + accountClusterId;
        return result;
    }
}
