/*
 * Copyright (c) 2009-2010 DuraSpace. All rights reserved.
 */
package org.duracloud.account.common.domain;

import org.duracloud.storage.domain.StorageProviderType;

import java.util.Set;

/**
 * Read-only summary of salient account details.
 *
 * @author "Daniel Bernstein (dbernstein@duraspace.org)"
 */
public class AccountInfo extends BaseDomainData {
    private String subdomain;
    private String acctName;
    private String orgName;
    private String department;
    private int paymentInfoId;
    private Set<Integer> instanceIds;
    private Set<StorageProviderType> storageProviders;

	public AccountInfo(int id,
                       String subdomain,
			           Set<StorageProviderType> storageProviders) {
		this(id, subdomain, null, null, null, -1, null, storageProviders, 0);
	}
	public AccountInfo(int id,
                       String subdomain,
                       String acctName,
                       String orgName,
			           String department,
                       int paymentInfoId,
                       Set<Integer> instanceIds,
			           Set<StorageProviderType> storageProviders) {
		this(id,
             subdomain,
             acctName,
             orgName,
             department,
             paymentInfoId,
             instanceIds,
             storageProviders,
             0);
	}

    public AccountInfo(int id,
                       String subdomain,
                       String acctName,
                       String orgName,
                       String department,
                       int paymentInfoId,
                       Set<Integer> instanceIds,
                       Set<StorageProviderType> storageProviders,
                       int counter) {
		super();
		this.id = id;
		this.subdomain = subdomain;
		this.acctName = acctName;
		this.orgName = orgName;
		this.department = department;
        this.paymentInfoId = paymentInfoId;
        this.instanceIds = instanceIds;
		this.storageProviders = storageProviders;
        this.counter = counter;
	}

	public String getSubdomain() {
		return subdomain;
	}

	public String getAcctName() {
		return acctName;
	}

	public String getOrgName() {
		return orgName;
	}

	public String getDepartment() {
		return department;
	}

	public int getPaymentInfoId() {
		return paymentInfoId;
	}

    public Set<Integer> getInstanceIds() {
        return instanceIds;
    }

    public Set<StorageProviderType> getStorageProviders() {
		return storageProviders;
	}

    /*
     * Generated by IntelliJ
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        AccountInfo that = (AccountInfo) o;

        if (paymentInfoId != that.paymentInfoId) {
            return false;
        }
        if (acctName != null ? !acctName.equals(that.acctName) :
            that.acctName != null) {
            return false;
        }
        if (department != null ? !department.equals(that.department) :
            that.department != null) {
            return false;
        }
        if (instanceIds != null ? !instanceIds.equals(that.instanceIds) :
            that.instanceIds != null) {
            return false;
        }
        if (orgName != null ? !orgName.equals(that.orgName) :
            that.orgName != null) {
            return false;
        }
        if (storageProviders != null ? !storageProviders
            .equals(that.storageProviders) : that.storageProviders != null) {
            return false;
        }
        if (subdomain != null ? !subdomain.equals(that.subdomain) :
            that.subdomain != null) {
            return false;
        }

        return true;
    }

    /*
     * Generated by IntelliJ
     */    
    @Override
    public int hashCode() {
        int result = subdomain != null ? subdomain.hashCode() : 0;
        result = 31 * result + (acctName != null ? acctName.hashCode() : 0);
        result = 31 * result + (orgName != null ? orgName.hashCode() : 0);
        result = 31 * result + (department != null ? department.hashCode() : 0);
        result = 31 * result + paymentInfoId;
        result =
            31 * result + (instanceIds != null ? instanceIds.hashCode() : 0);
        result = 31 * result +
            (storageProviders != null ? storageProviders.hashCode() : 0);
        return result;
    }
}
