/*
 * Copyright (c) 2009-2010 DuraSpace. All rights reserved.
 */
package org.duracloud.account.common.domain;

import java.util.Set;

/**
 * Contains a listing of a user's roles for a specific account.
 *
 * @author: Bill Branan
 * Date: Dec 2, 2010
 */
public class AccountRights extends BaseDomainData {

    private int accountId;
    private int userId;
    private Set<Role> roles;

    public AccountRights(int id,
                         int accountId,
                         int userId,
                         Set<Role> roles) {
        this(id, accountId, userId, roles, 0);
    }

    public AccountRights(int id,
                         int accountId,
                         int userId,
                         Set<Role> roles,
                         int counter) {
        this.id = id;
        this.accountId = accountId;
        this.userId = userId;
        this.roles = roles;
        this.counter = counter;
    }

    public int getAccountId() {
        return accountId;
    }

    public int getUserId() {
        return userId;
    }

    public Set<Role> getRoles() {
        return roles;
    }

    /*
     * Generated by IntelliJ
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        AccountRights that = (AccountRights) o;

        if (accountId != that.accountId) {
            return false;
        }
        if (userId != that.userId) {
            return false;
        }
        if (roles != null ? !roles.equals(that.roles) : that.roles != null) {
            return false;
        }

        return true;
    }

    /* 
     * Generated by IntelliJ
     */
    @Override
    public int hashCode() {
        int result = accountId;
        result = 31 * result + userId;
        result = 31 * result + (roles != null ? roles.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(accountId);
        sb.append(":");
        sb.append(userId);
        sb.append(":");
        sb.append(roles);
        return sb.toString();
    }
}
