/*
 * Copyright (c) 2009-2012 DuraSpace. All rights reserved.
 */
package org.duracloud.account.common.domain;

import java.io.IOException;
import java.io.Serializable;
import java.util.Set;

/**
 * @author: Bill Branan
 * Date: 2/16/12
 */
public class AccountCluster extends BaseDomainData implements Serializable{

    private static final long serialVersionUID = 1L;

    private String clusterName;

    /**
     * The IDs of all Accounts which are part of the cluster
     */
    private Set<Integer> clusterAccountIds;

    public AccountCluster(int id,
                          String clusterName,
                          Set<Integer> clusterAccountIds) {
        this(id, clusterName, clusterAccountIds, 0);
    }

    public AccountCluster(int id,
                          String clusterName,
                          Set<Integer> clusterAccountIds,
                          int counter) {
        this.id = id;
        this.clusterName = clusterName;
        this.clusterAccountIds = clusterAccountIds;
        this.counter = counter;
    }

    public String getClusterName() {
        return clusterName;
    }

    public void setClusterName(String clusterName) {
        this.clusterName = clusterName;
    }

    public Set<Integer> getClusterAccountIds() {
        return clusterAccountIds;
    }

    public void setClusterAccountIds(Set<Integer> clusterAccountIds) {
        this.clusterAccountIds = clusterAccountIds;
    }

    /**
     * Generated by IntelliJ
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        AccountCluster that = (AccountCluster) o;

        if (clusterAccountIds != null ? !clusterAccountIds
            .equals(that.clusterAccountIds) : that.clusterAccountIds != null) {
            return false;
        }
        if (clusterName != null ? !clusterName.equals(that.clusterName) :
            that.clusterName != null) {
            return false;
        }

        return true;
    }

    /**
     * Generated by IntelliJ
     */
    @Override
    public int hashCode() {
        int result = clusterName != null ? clusterName.hashCode() : 0;
        result = 31 * result +
            (clusterAccountIds != null ? clusterAccountIds.hashCode() : 0);
        return result;
    }

    private void writeObject(java.io.ObjectOutputStream out)
        throws IOException{
        out.defaultWriteObject();
        out.writeInt(this.id);
        out.writeInt(this.counter);
    }

    private void readObject(java.io.ObjectInputStream in)
        throws IOException, ClassNotFoundException{
        in.defaultReadObject();
        this.id = in.readInt();
        this.counter = in.readInt();
    }
}
