/*
 * Copyright (c) 2009-2010 DuraSpace. All rights reserved.
 */
package org.duracloud.account.common.domain;

/**
 * @author Bill Branan
 *         Date: Dec 17, 2010
 */
public class DuracloudInstance extends BaseDomainData {

    /**
     * The ID of the Image on which this instance is based.
     */
    private int imageId;

    /**
     * The ID of the Account for which this instance was created
     */
    private int accountId;

    /**
     * The host name at which this instance is available.
     */
    private String hostName;

    /**
     * The identifier value assigned to this machine instance by the compute
     * provider. This ID is used when starting, stopping, or restarting the
     * server on which the DuraCloud software is running.
     */
    private String providerInstanceId;

    public DuracloudInstance(int id,
                             int imageId,
                             int accountId,
                             String hostName,
                             String providerInstanceId) {
        this(id,
             imageId,
             accountId,
             hostName,
             providerInstanceId,
             0);
    }

    public DuracloudInstance(int id,
                             int imageId,
                             int accountId,
                             String hostName,
                             String providerInstanceId,
                             int counter) {
        this.id = id;
        this.imageId = imageId;
        this.accountId = accountId;
        this.hostName = hostName;
        this.providerInstanceId = providerInstanceId;
        this.counter = counter;
    }

    public int getImageId() {
        return imageId;
    }

    public int getAccountId() {
        return accountId;
    }

    public String getHostName() {
        return hostName;
    }

    public String getProviderInstanceId() {
        return providerInstanceId;
    }

    /*
     * Generated by IntelliJ
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        DuracloudInstance that = (DuracloudInstance) o;

        if (accountId != that.accountId) {
            return false;
        }
        if (imageId != that.imageId) {
            return false;
        }
        if (hostName != null ? !hostName.equals(that.hostName) :
            that.hostName != null) {
            return false;
        }
        if (providerInstanceId != null ? !providerInstanceId
            .equals(that.providerInstanceId) :
            that.providerInstanceId != null) {
            return false;
        }

        return true;
    }

    /*
     * Generated by IntelliJ
     */
    @Override
    public int hashCode() {
        int result = imageId;
        result = 31 * result + accountId;
        result = 31 * result + (hostName != null ? hostName.hashCode() : 0);
        result = 31 * result +
            (providerInstanceId != null ? providerInstanceId.hashCode() : 0);
        return result;
    }

}
