/*
 * Copyright (c) 2009-2010 DuraSpace. All rights reserved.
 */
package org.duracloud.account.common.domain;

import java.util.Set;

/**
 * @author Bill Branan
 *         Date: Dec 17, 2010
 */
public class DuracloudInstance extends BaseDomainData {

    /**
     * The ID of the Image on which this instance is based.
     */
    private int imageId;

    /**
     * The host name at which this instance is available.
     */
    private String hostName;

    /**
     * The identifier value assigned to this machine instance by the compute
     * provider. This ID is used when starting, stopping, or restarting the
     * server on which the DuraCloud software is running.
     */
    private String providerInstanceId;

    /**
     * The ID of the ComputeProviderAccount which is the compute provider for
     * an instance
     */
    private int computeProviderAccountId;

    /**
     * The ID of a StorageProviderAccount which is used for primary storage
     */
    private int primaryStorageProviderAccountId;

    /**
     * The IDs of all StorageProviderAccounts which are used for secondary storage
     */
    private Set<Integer> secondaryStorageProviderAccountIds;

    /**
     * The IDs of all ServiceRepositories used to store service binaries
     */
    private Set<Integer> serviceRepositoryIds;

    public DuracloudInstance(int id,
                             int imageId,
                             String hostName,
                             String providerInstanceId,
                             int computeProviderAccountId,
                             int primaryStorageProviderAccountId,
                             Set<Integer> secondaryStorageProviderAccountIds,
                             Set<Integer> serviceRepositoryIds) {
        this(id,
             imageId,
             hostName,
             providerInstanceId,
             computeProviderAccountId,
             primaryStorageProviderAccountId,
             secondaryStorageProviderAccountIds,
             serviceRepositoryIds,
             0);
    }

    public DuracloudInstance(int id,
                             int imageId,
                             String hostName,
                             String providerInstanceId,
                             int computeProviderAccountId,
                             int primaryStorageProviderAccountId,
                             Set<Integer> secondaryStorageProviderAccountIds,
                             Set<Integer> serviceRepositoryIds,
                             int counter) {
        this.id = id;
        this.imageId = imageId;
        this.hostName = hostName;
        this.providerInstanceId = providerInstanceId;
        this.computeProviderAccountId = computeProviderAccountId;
        this.primaryStorageProviderAccountId = primaryStorageProviderAccountId;
        this.secondaryStorageProviderAccountIds = secondaryStorageProviderAccountIds;
        this.serviceRepositoryIds = serviceRepositoryIds;
        this.counter = counter;
    }

    public int getImageId() {
        return imageId;
    }

    public String getHostName() {
        return hostName;
    }

    public String getProviderInstanceId() {
        return providerInstanceId;
    }

    public int getComputeProviderAccountId() {
        return computeProviderAccountId;
    }

    public int getPrimaryStorageProviderAccountId() {
        return primaryStorageProviderAccountId;
    }

    public Set<Integer> getSecondaryStorageProviderAccountIds() {
        return secondaryStorageProviderAccountIds;
    }

    public Set<Integer> getServiceRepositoryIds() {
        return serviceRepositoryIds;
    }

    /*
     * Generated by IntelliJ
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        DuracloudInstance that = (DuracloudInstance) o;

        if (computeProviderAccountId != that.computeProviderAccountId) {
            return false;
        }
        if (imageId != that.imageId) {
            return false;
        }
        if (primaryStorageProviderAccountId !=
            that.primaryStorageProviderAccountId) {
            return false;
        }
        if (hostName != null ? !hostName.equals(that.hostName) :
            that.hostName != null) {
            return false;
        }
        if (providerInstanceId != null ? !providerInstanceId
            .equals(that.providerInstanceId) :
            that.providerInstanceId != null) {
            return false;
        }
        if (secondaryStorageProviderAccountIds !=
            null ? !secondaryStorageProviderAccountIds
            .equals(that.secondaryStorageProviderAccountIds) :
            that.secondaryStorageProviderAccountIds != null) {
            return false;
        }
        if (serviceRepositoryIds != null ? !serviceRepositoryIds
            .equals(that.serviceRepositoryIds) :
            that.serviceRepositoryIds != null) {
            return false;
        }

        return true;
    }

    /*
     * Generated by IntelliJ
     */
    @Override
    public int hashCode() {
        int result = imageId;
        result = 31 * result + (hostName != null ? hostName.hashCode() : 0);
        result = 31 * result +
            (providerInstanceId != null ? providerInstanceId.hashCode() : 0);
        result = 31 * result + computeProviderAccountId;
        result = 31 * result + primaryStorageProviderAccountId;
        result = 31 * result + (secondaryStorageProviderAccountIds !=
            null ? secondaryStorageProviderAccountIds.hashCode() : 0);
        result = 31 * result +
            (serviceRepositoryIds != null ? serviceRepositoryIds
                .hashCode() : 0);
        return result;
    }

}
