/*
 * Copyright (c) 2009-2010 DuraSpace. All rights reserved.
 */
package org.duracloud.account.common.domain;

/**
 * @author: Bill Branan
 * Date: Feb 1, 2010
 */
public class ServerImage extends BaseDomainData {

    /**
     * The ID of the ProviderAccount on which this server image is hosted.
     */
    private int providerAccountId;

    /**
     * The ID given to this image by the hosting provider. This will likely
     * have a different name at each provider (e.g. at Amazon this is the
     * AMI ID, the Amazon Machine Image Identifier).
     */
    private String providerImageId;

    /**
     * The version of the DuraCloud software loaded on this image.
     */
    private String version;

    /**
     * Description of the image.
     */
    private String description;

    public ServerImage(int id,
                       int providerAccountId,
                       String providerImageId,
                       String version,
                       String description) {
        this(id, providerAccountId, providerImageId, version, description, 0);
    }

    public ServerImage(int id,
                       int providerAccountId,
                       String providerImageId,
                       String version,
                       String description,
                       int counter) {
        this.id = id;
        this.providerAccountId = providerAccountId;
        this.providerImageId = providerImageId;
        this.version = version;
        this.description = description;
        this.counter = counter;
    }

    public int getProviderAccountId() {
        return providerAccountId;
    }

    public String getProviderImageId() {
        return providerImageId;
    }

    public String getVersion() {
        return version;
    }

    public String getDescription() {
        return description;
    }

    /*
     * Generated by IntelliJ
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        ServerImage that = (ServerImage) o;

        if (providerAccountId != that.providerAccountId) {
            return false;
        }
        if (description != null ? !description.equals(that.description) :
            that.description != null) {
            return false;
        }
        if (providerImageId != null ? !providerImageId
            .equals(that.providerImageId) : that.providerImageId != null) {
            return false;
        }
        if (version != null ? !version.equals(that.version) :
            that.version != null) {
            return false;
        }

        return true;
    }

    /*
     * Generated by IntelliJ
     */    
    @Override
    public int hashCode() {
        int result = providerAccountId;
        result = 31 * result +
            (providerImageId != null ? providerImageId.hashCode() : 0);
        result = 31 * result + (version != null ? version.hashCode() : 0);
        result =
            31 * result + (description != null ? description.hashCode() : 0);
        return result;
    }
}
