/*
 * Copyright (c) 2009-2012 DuraSpace. All rights reserved.
 */
package org.duracloud.account.common.domain;

import java.util.Set;

/**
 * @author: Bill Branan
 * Date: 2/8/12
 */
public class ServerDetails extends BaseDomainData {

    /**
     * The ID of the ComputeProviderAccount which is the compute provider for
     * an instance
     */
    private int computeProviderAccountId;

    /**
     * The ID of a StorageProviderAccount which is used for primary storage
     */
    private int primaryStorageProviderAccountId;

    /**
     * The IDs of all StorageProviderAccounts which are used for secondary storage
     */
    private Set<Integer> secondaryStorageProviderAccountIds;



	public ServerDetails(int id,
                         int computeProviderAccountId,
                         int primaryStorageProviderAccountId,
                         Set<Integer> secondaryStorageProviderAccountIds) {
		this(id,
             computeProviderAccountId,
             primaryStorageProviderAccountId,
             secondaryStorageProviderAccountIds,
             0);
	}

    public ServerDetails(int id,
                       int computeProviderAccountId,
                       int primaryStorageProviderAccountId,
                       Set<Integer> secondaryStorageProviderAccountIds,
                       int counter) {
		super();
		this.id = id;
        this.computeProviderAccountId = computeProviderAccountId;
        this.primaryStorageProviderAccountId = primaryStorageProviderAccountId;
        this.secondaryStorageProviderAccountIds = secondaryStorageProviderAccountIds;
        this.counter = counter;
	}

    public int getComputeProviderAccountId() {
        return computeProviderAccountId;
    }

    public int getPrimaryStorageProviderAccountId() {
        return primaryStorageProviderAccountId;
    }

    public Set<Integer> getSecondaryStorageProviderAccountIds() {
        return secondaryStorageProviderAccountIds;
    }

    /*
     * Generated by IntelliJ
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        ServerDetails that = (ServerDetails) o;

        if (computeProviderAccountId != that.computeProviderAccountId) {
            return false;
        }
        if (primaryStorageProviderAccountId !=
            that.primaryStorageProviderAccountId) {
            return false;
        }
        if (secondaryStorageProviderAccountIds !=
            null ? !secondaryStorageProviderAccountIds
            .equals(that.secondaryStorageProviderAccountIds) :
            that.secondaryStorageProviderAccountIds != null) {
            return false;
        }

        return true;
    }

    /*
     * Generated by IntelliJ
     */
    @Override
    public int hashCode() {
        int result = computeProviderAccountId;
        result = 31 * result + primaryStorageProviderAccountId;
        result = 31 * result + (secondaryStorageProviderAccountIds !=
            null ? secondaryStorageProviderAccountIds.hashCode() : 0);
        return result;
    }

}
